"""Argument grammar for the AgentBus command-line client."""

from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Local service lifecycle and HTTP client for the superworkspace AgentBus."
    )
    commands = parser.add_subparsers(dest="command", required=True)
    for name in ("serve", "start", "stop", "status", "autostart"):
        commands.add_parser(name)
    send = commands.add_parser("send", help="Publish a message to the configured Slack channel")
    send.add_argument("text", help="Message text, or - to read stdin")
    send.add_argument("--identity")
    send.add_argument("--sender")
    send.add_argument("--recipient", "--to")
    send.add_argument("--broadcast", action="store_true")
    send.add_argument("--informational", action="store_true")
    send.add_argument("--kind", default="message")
    send.add_argument("--repo")
    send.add_argument("--correlation-id")
    send.add_argument("--thread-ts")
    send.add_argument("--reply-to-cursor", type=int)
    read = commands.add_parser("read", help="Read the durable local inbox")
    read.add_argument("--after", type=int, default=0)
    read.add_argument("--limit", type=int, default=100)
    read.add_argument("--recipient")
    read.add_argument("--thread-ts")
    onboard = commands.add_parser("onboard", help="Create a unique local chat identity and persona")
    onboard.add_argument("--repo")
    onboard.add_argument("--name", required=True)
    onboard.add_argument("--role", required=True)
    onboard.add_argument("--display-name")
    onboard.add_argument("--voice", default="direct, practical, and collaborative")
    onboard.add_argument("--remit")
    onboard.add_argument("--values", default="clarity, care, and useful results")
    onboard.add_argument("--working-style", default="inspect, act, verify, and communicate")
    onboard.add_argument("--signature", default="a distinct but grounded presence")
    onboard.add_argument("--persona-file")
    onboard.add_argument("--from", dest="start_from", choices=("now", "beginning"), default="now")
    onboard.add_argument("--announce", nargs="?", const="")
    onboard.add_argument("--resume", action="store_true")
    persona = commands.add_parser("persona", help="Print a chat's persona and adoption instructions")
    persona.add_argument("--identity")
    persona.add_argument("--json", action="store_true")
    persona.add_argument("--display-name")
    persona.add_argument("--role")
    persona.add_argument("--voice")
    persona.add_argument("--remit")
    persona.add_argument("--values")
    persona.add_argument("--working-style")
    persona.add_argument("--signature")
    persona.add_argument("--persona-file")
    agents = commands.add_parser("agents", help="List local AgentBus chat profiles")
    agents.add_argument("--json", action="store_true")
    inbox = commands.add_parser("inbox", help="Read a chat inbox without acknowledging it")
    inbox.add_argument("--identity")
    inbox.add_argument("--after", type=int)
    inbox.add_argument("--limit", type=int, default=100)
    inbox.add_argument("--thread-ts")
    inbox.add_argument("--context", action="store_true")
    ack = commands.add_parser("ack", help="Acknowledge handled messages through a cursor")
    ack.add_argument("--identity")
    ack.add_argument("--through", type=int, required=True)
    rebind = commands.add_parser("rebind", help="Bind a profile to this inbox and choose its durable cursor")
    rebind.add_argument("--identity")
    rebind.add_argument("--from", dest="start_from", choices=("now", "beginning"), required=True)
    claim = commands.add_parser("claim", help="Atomically claim an unrouted message")
    claim.add_argument("--identity")
    claim.add_argument("--cursor", type=int, required=True)
    reply = commands.add_parser("reply", help="Reply to a message by local cursor")
    reply.add_argument("text", help="Reply text, or - to read stdin")
    reply.add_argument("--identity")
    reply.add_argument("--to-cursor", type=int, required=True)
    handoff = commands.add_parser("issue-handoff", help="Operator: authorize migration of a local profile UUID")
    handoff.add_argument("--identity")
    handoff.add_argument("--output", required=True)
    join = commands.add_parser("join", help="Join the operator control plane using a private handoff file")
    join.add_argument("--identity")
    join.add_argument("--handoff-file")
    policy_ack = commands.add_parser("policy-ack", help="Acknowledge the exact delivered policy revision")
    policy_ack.add_argument("--identity")
    policy_ack.add_argument("revision")
    check_in = commands.add_parser("check-in", help="Check for operator control and policy changes")
    check_in.add_argument("--identity")
    control_ack = commands.add_parser("ack-control", help="Acknowledge an operator control for this session")
    control_ack.add_argument("--identity")
    control_ack.add_argument("control_id")
    control_ack.add_argument("--report-file")
    poll = commands.add_parser("poll", help="Wait silently for a semantic participation event")
    poll.add_argument("--identity")
    poll.add_argument("--json", action="store_true")
    policy_set = commands.add_parser("policy-set", help="Operator: create a revisioned policy")
    policy_set.add_argument("--scope", choices=("global", "repo", "chat"), required=True)
    policy_set.add_argument("--scope-key", required=True)
    policy_set.add_argument("--values-file", required=True)
    policy_show = commands.add_parser("policy-show", help="Show effective policy and provenance")
    policy_show.add_argument("--repo", required=True)
    policy_show.add_argument("--chat-id", required=True)
    control_stop = commands.add_parser("control-stop", help="Operator: issue a durable stop")
    target = control_stop.add_mutually_exclusive_group(required=True)
    target.add_argument("--to", action="append")
    target.add_argument("--all", action="store_true")
    control_stop.add_argument("--reason", required=True)
    control_issue = commands.add_parser("control-issue", help="Operator: issue nudge or checkpoint request")
    control_issue.add_argument("--kind", choices=("nudge", "checkpoint_request"), required=True)
    auxiliary_target = control_issue.add_mutually_exclusive_group(required=True)
    auxiliary_target.add_argument("--to", action="append")
    auxiliary_target.add_argument("--all", action="store_true")
    control_issue.add_argument("--reason", required=True)
    control_status = commands.add_parser("control-status", help="Operator: inspect per-target stop state")
    control_status.add_argument("control_id")
    presence = commands.add_parser("session-presence", help="Operator: inspect target participation")
    presence.add_argument("session_id")
    rename = commands.add_parser("rename", help="Change this chat's route while preserving its UUID")
    rename.add_argument("--identity")
    rename.add_argument("--name", required=True)
    recovery = commands.add_parser("claim-recovery", help="Operator: release or reassign an unrouted claim")
    recovery.add_argument("--cursor", type=int, required=True)
    recovery.add_argument("--to")
    recovery.add_argument("--reason", required=True)
    return parser


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    return build_parser().parse_args(argv)
